### PR TITLE
chore: Remove unused import

### PR DESCRIPTION
**Pull request by laglangyue**
This PR includes:
 such as title,remvoe some not import package
motivations:
I find there are some waning about `unused`
test:
Removed some `unused import`, so I just compiled locally,it will test by CI

### CODE REVIEW

**Comment by laglangyue** [comment]
I also find a warning about thie,But I think that this may be a false warning.

```shell
[warn] /home/laglang/coding/incubator-pekko-http/parsing/src/main/scala-2/org/apache/pekko/http/ccompat/pre213macro.scala:17:36: Unused import
[warn] import scala.language.experimental.macros
[warn]                                    ^
[warn] /home/laglang/coding/incubator-pekko-http/parsing/src/main/scala-2/org/apache/pekko/http/ccompat/since213macro.scala:17:36: Unused import
[warn] import scala.language.experimental.macros

```

**Comment by pjfanning** [comment]
this breaks the scala 2.12 build - please close this

**Comment by laglangyue** [comment]
> this breaks the scala 2.12 build - please close this

Sorry,I didn't test it carefully on 2.12 before, and I still think  some imports  are not related to the scala version. I will review this PR again

**Review by mdedetrich — APPROVED** [review]
lgtm, everything is compiling

**Review by He-Pin — APPROVED** [review]
lgtm

**Pull request merged**
