### PR TITLE
update version of sbt-scalafix to 0.11.1

### PR DESCRIPTION
**Pull request by laglangyue**
sbt-scalafix:0.11.1 is released
and I can't build with 0.11.0

### CODE REVIEW

**Comment by pjfanning** [comment]
Could you please more detail? - like what is not working

**Comment by laglangyue** [comment]
> Could you please more detail? - like what is not working
sorry, I can't download sbt-scalafix:0.11.0,and download 0.11.1 successful.
then I go to `https://search.maven.org` and find 0.11.1
image

**Comment by laglangyue** [comment]
besides,it's my sbt repositories

local
aliyun: https://maven.aliyun.com/repository/public/
apache-snapshots: https://repository.apache.org/content/repositories/snapshots/
sbt-plugin-repo: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
maven-central: https://repo1.maven.org/maven2/

**Comment by pjfanning** [comment]
These are the 0.11.0 jars - https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalafix_2.12_1.0/0.11.0/

sbt plugins have `_1.0` appended to their name to say that this is the jar needed for sbt 1.x.

**Review by pjfanning — APPROVED** [review]
lgtm - not necessary but probably ok

**Pull request merged**
