### PR TITLE
scala 2.13.12

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by mdedetrich** [comment]
Also need to update https://github.com/apache/incubator-pekko-http/blob/8815ed47a7f71f7e6f011b3de403f69cd3bb8748/scripts/link-validator.conf#L56

**Comment by pjfanning** [comment]
> Also need to update
> 
> https://github.com/apache/incubator-pekko-http/blob/8815ed47a7f71f7e6f011b3de403f69cd3bb8748/scripts/link-validator.conf#L56

thanks - I've committed a fix for that now

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
Also backport to 1.0.x

**Pull request merged**
