### PR TITLE
Fix remaining package/dir problems

### PR DESCRIPTION
**Pull request by mdedetrich**
There was some remaining package names/source file locations which was missed in previous PR's

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
looks like there are some issues in build.sbt

**Comment by mdedetrich** [comment]
> looks like there are some issues in build.sbt

Just fixed them

**Review by jrudolph — APPROVED** [review]
lgtm

**Pull request merged**
