### PR TITLE
fix more issues with legacy Akka naming

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by mdedetrich** [comment]
@pjfanning Apologies but my javafmt commit caused some merge conflicts on this PR but they are relatively minor. If you do a rebase on `origin/main` and run `sbt javafmt` it should remove the conflicts.

**Comment by pjfanning** [comment]
@mdedetrich I was aware that it would happen. I have fixed the merge conflicts now.

**Comment by mdedetrich** [comment]
Do you want this to be reviewed, you didn't assign any reviewers?

**Comment by pjfanning** [comment]
I typically wait for a clean CI run before assigning reviewers

**Comment by pjfanning** [comment]
@mdedetrich no hurry on merging this but I think it is safe to merge and that it doesn't have any effect (good or bad) on the scaladoc generation issue

**Comment by mdedetrich** [comment]
Noted, I will check it after I fix the pekko docs

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
