### PR TITLE
Update Scala to 2.13.12

### PR DESCRIPTION
**Pull request by pjfanning**
backports #358

### CODE REVIEW

**Comment by pjfanning** [comment]
@mdedetrich scala 3.3.1 causes a large MiMa set of failures - so I'm reverting this to just update Scala 2.13.12

**Comment by mdedetrich** [comment]
> @mdedetrich scala 3.3.1 causes a large MiMa set of failures - so I'm reverting this to just update Scala 2.13.12
> 
> https://github.com/apache/incubator-pekko-http/actions/runs/6710688953/job/18236439678?pr=360

@pjfanning This is extremely fishy, let me check on Scala discord about this

**Comment by mdedetrich** [comment]
@pjfanning I think I remember the core issue, you need to update sbt-mima to its latest version. I had to do the same with pekko core

**Comment by pjfanning** [comment]
@mdedetrich I'll keep this PR just for Scala 2.13 and will do separate backports for mima plugin and scala 3.3.1

**Comment by pjfanning** [comment]
@mdedetrich do you think this PR can be merged?

**Review by He-Pin — APPROVED** [review]
Lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
> scala 3.3.1 causes a large MiMa set of failures - so I'm reverting this to just update Scala 2.13.12

I also previously just ignored `IncompatibleSignatureProblem` errors in mima. They are arguably not strict binary compatibility problems since the types are erased anyway and the signature is not used at runtime but only required for source compilation.

**Pull request merged**
