### PR TITLE
!sbt Use multiJvmPlugin from pekko.

### PR DESCRIPTION
**Pull request by He-Pin**
Just copy code from pekko, better to submit this upstream, will do later.

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
approved as temporary solution - if it doesn't help, we should probably revert this - if it does work, we should be looking at creating a shared sbt plugin with this change

**Comment by jrudolph** [comment]
What problem does it solve?

**Comment by He-Pin** [comment]
> What problem does it solve?
> 

It start the Player only after The Controller can be connected.

**Comment by mdedetrich** [comment]
> approved as temporary solution - if it doesn't help, we should probably revert this - if it does work, we should be looking at creating a shared sbt plugin with this change

@pjfanning This is probably a good candidate to include in the `incubator-pekko-sbt-build` I was talking about

**Comment by He-Pin** [comment]
That's true, the sbt one seems unmaintained at least for now.

**Comment by He-Pin** [comment]
@mdedetrich 
 1. We need wait the `Controller` transited to connectable before start the `Player`.
 2. Need submit a PR to `sbt-multi-jvm` and waiting a new snapshot, which may take sometimes and is not a *quick fix*.
 3. I did not diff the code with sbt-multi-jvm line by line, but there must be some reason for Akka was keep it separately

**Comment by mdedetrich** [comment]
@He-Pin Lets discuss in https://github.com/apache/incubator-pekko/issues/548

**Comment by jrudolph** [comment]
Where did the problem occur and how was it fixed? Which kubernetes cluster
are we connecting against here?

Matthew de Detrich ***@***.***> schrieb am Di., 8. Aug. 2023,
09:12:

**Comment by He-Pin** [comment]
@jrudolph After migrate the `netty3` to `netty4`, the `Contoller` part which started at `index==0` seems not bind faster enough. The thread model has been changed in netty 4, or the max attept in the `Player` can be changed to a larger value, does that's what you expected?

**Comment by He-Pin** [comment]
Let's me submit a fix and then this code will not be needed.

**Pull request merged**
