### PR TITLE
replace usages of akka.io in tests

### PR DESCRIPTION
**Pull request by jrudolph**
Refs #49

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
So some tests are failing, I suspect that the tests may have been relying on behaviour from akka.io

**Comment by jrudolph** [comment]
> So some tests are failing, I suspect that the tests may have been relying on behaviour from akka.io

Probably only the expected error messages need to be fixed

**Comment by mdedetrich** [comment]
Might be excessive and definitely something later down the track, but there may be merit in using something like https://dev.to/iurysza/setting-up-mockserver-3kbe

**Comment by jrudolph** [comment]
> Might be excessive and definitely something later down the track, but there may be merit in using something like [dev.to/iurysza/setting-up-mockserver-3kbe](https://dev.to/iurysza/setting-up-mockserver-3kbe)

I'm not even sure if any of the tests even actually run. Most are either using the URL as an example string or showing usages in the docs.

**Pull request merged**
