### PR TITLE
add extra license header to DateTime.scala corresponding to note in LICENSE

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by justinmclean** [comment]
I would assume as this is 3rd party code it's not copyright Lightbend Inc or the ASF??

**Comment by mdedetrich** [comment]
> I would assume as this is 3rd party code it's not copyright Lightbend Inc or the ASF??

Its code that was written by Lightbend that was based off of ASF code

**Comment by mdedetrich** [comment]
This was also clearly decided upon in https://issues.apache.org/jira/browse/LEGAL-626, we are not allowed to remove the existing Lightbend copyright header from code that was taken from Akka (which is the case here).

**Comment by justinmclean** [comment]
Without permission no, so probably best to leave it there, it's unfortunate they copies someone else code.

**Pull request merged**
